### ISSUE TITLE
Contact e-mail

### ISSUE THREAD

**Issue by bmaschio** [jolie/website#11]
@jolie/developers 

Would be not nice to have a contact e-mail where interested ppl could contact us? I am up to managing the communication

**Comment by fmontesi** [comment]
We have jolie-devel@googlegroups.com and webmaster@jolie-lang.org already.
Are you thinking about another one of different nature?

**Comment by bmaschio** [comment]
I was thinking something like business@jolie-lang.org where people can ask more business orientated questions? My idea is to give a feeling that is both a solid research project but a valid tool to do enterprise applications

**Comment by mwallnoefer** [comment]
We have added a link to _Discord_ (on the top-left corner) and otherwise we have the webmaster contact in the footer, so this should be ok.
