### ISSUE TITLE
Installation instruction for the supported editor

### ISSUE THREAD

**Issue by bmaschio** [jolie/website#14]
@jolie/developers 

I have noticed that there are some problems when installing Atom under windows. if the pc uses a  anti virus it often blocks the installation. Would be also nice to have a versioning table  so the user can know what version of atom under what OS works and if the Jolie package works fully or only partially
So it goes also for the other editors

Thanks 

Balint

**Comment by fmontesi** [comment]
@thesave what should we do here?

**Comment by thesave** [comment]
Uhm, what about we keep an "unmaintained" section of plugins for editors on the editors page?
I will not maintain the Sublime Text plugin anymore. I do not know for the others.
However, I think now we should concentrate to get the experience right on one platform - vscode being the most promising/advanced we have

**Comment by bmaschio** [comment]
I think we should go for VsCode and that all

**Comment by fmontesi** [comment]
I agree as well with your suggestion @thesave

**Comment by thesave** [comment]
Perfect, I added a section called "Unmaintained plugins" under the downloads page on the website stating that.
