### ISSUE TITLE
Documentation for type choices

### ISSUE THREAD

**Issue by fmontesi** [jolie/website#17]
@agwe Could you add some documentation for type choices to the website here? @thesave Can you point out to @agwe where she should add it?

**Comment by thesave** [comment]
For the declaration [here](https://github.com/jolie/website/blob/master/docs/documentation/basics/communication_ports.md#type-choice). 
For the usage (e.g. `instanceof`) [here](https://github.com/jolie/website/blob/master/docs/documentation/basics/handling_simple_data.md#casting-and-checking-variable-types).

**Comment by lsafina** [comment]
> For the declaration here. 

looks like the documentation is already done.  Is there anything else to be added?

> For the usage (e.g. instanceof) here.

Is it ok if I add the example like this:

```
type numeric: int | double
main
{
  in = 1;
  db = 1.0;
  n = in instanceof numeric; // n = true
  n = db instanceof numeric // n = true 
}

```

**Comment by fmontesi** [comment]
On the declaration: I think that an example where we have subnodes may be helpful.

On instanceof, I think that we could have two examples. One is Larisa's example, which shows that two different things can have the same choice type. Another we could show is to use instanceof to understand which choice in the type we have, e.g.,

```
type number: int | long | double

main
{
    getNumber( n );
    if ( n instanceof int ) {
        /* ... */
    } else if n instanceof long ) {
        /* ... */
    } else if ( n instanceof double {
        /* ... */
    } else {
        /* ... */
    }
}
```

What do you think?

**Comment by lsafina** [comment]
Something like this? https://github.com/jolie/website/pull/19

There is an example for subnodes in declaration section

```
//choice with subtypes
type subtypes: void {.id: string | int}
```

Should I rewrite it?

**Comment by fmontesi** [comment]
Great! @thesave , can you check @agwe 's pull request?

**Comment by thesave** [comment]
Thanks for you contribution @agwe. Merged and fixed/added some links.
