### ISSUE TITLE
Documentation about HTTP alias is missing

### ISSUE THREAD

**Issue by klag** [jolie/website#22]

**Comment by thesave** [comment]
Please, @klag can you be more specific? For instance, giving an example of what is missing (I guess you mean a different aliasing wrt [this](https://github.com/jolie/website/blob/master/docs/documentation/protocols/code/http.iol#L185)).

**Comment by klag** [comment]
I think it is necessary to introduce a brief section where they are explained with some simple example. Otherwise it is difficult for the reader to understand when and how to use them

**Comment by thesave** [comment]
You are right @klag. Actually, the documentation of web applications is a little scattered between the page on Leonardo and the one on Rest Services.

It could be better to add a page dedicated to "Web Application Patterns" under the "[Web Applications](https://github.com/jolie/website/tree/master/docs/documentation/web_applications)" category where we can move concepts loosely related to Leonardo (like [querystrings](https://github.com/jolie/website/blob/master/docs/documentation/web_applications/leonardo.md#html-querystrings) and [html forms](https://github.com/jolie/website/blob/master/docs/documentation/web_applications/leonardo.md#jquery)) and where we explain how to use/implement (unordered):

- cookies (possibly moving from the Leonardo page and extending the documentation on [cookies](https://github.com/jolie/website/blob/master/docs/documentation/web_applications/leonardo.md#using-cookie) written by @bmaschio);
- aliases (i.e., mappings operations <-> urls);
- headers (e.g., basic assignment and retrieval, how to implement basic HTTP access authentication)
- other staple elements of web application programming (taking care of pointing to the possible related elements in the [rest_services](https://github.com/jolie/website/blob/master/docs/documentation/rest_services/rest_services.md) page, e.g., routing).

What do you think about it?

**Comment by bmaschio** [comment]
@thesave @klag 
I think we could  devide the HTTP information as  Jolie used as HTTP server or  Jolie as HTTP client and  there  showing sort of scenario one may find to deal with. This may help the Jolie solution  programmer that wants to work with both clients and server HTTP i can decompose the problems in parts
For example we could have 
- "How to handle incoming cookies"
- "How to set outgoing cookies"

and so on with headers  http error message type ecc ecc
Tnk
Balint

**Comment by thesave** [comment]
Right. I see the two solutions as incremental. We could start by extracting the mentioned patterns into a dedicated page and then, when we have enough patterns/examples, we could split the page between clients and servers.

**Comment by bmaschio** [comment]
@thesave I agree do you want a hand?

**Comment by thesave** [comment]
Sorry for the late reply @bmaschio. I definitely welcome a hand :)

A first iteration on this should deal with moving the material from the mentioned pages into a new, dedicated page (e.g., "Web Application Patterns"). We need to be careful when moving existing documentation pieces to preserve external references, e.g., an external link to 
`web_applications/leonardo.html#html-querystrings` should point the user to where we moved that piece of information (e.g., a label/panel reporting the move).

I'll give it a go today and report here as soon as I've pushed a stable procedure for it.

**Comment by thesave** [comment]
Hi, I created a branch [1] to ease the transition to/creation of the Web Application Patterns page.
Right now I just transferred the "cookies" section in leonardo.md to the new page [2].

@klag, @bmaschio can you contribute in the page, e.g., with draft sections on headers (how to read/set them) and aliases?

[1] https://github.com/jolie/website/tree/Web-Application-Patterns
[2] https://github.com/jolie/website/blob/Web-Application-Patterns/docs/documentation/web_applications/web_application_patterns.md

**Comment by mwallnoefer** [comment]
Seems to be handled by the docs portal by now: https://docs.jolie-lang.org/
