### ISSUE TITLE
Document new build system

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/website#28]
We need to document the new build system (mvn) on https://www.jolie-lang.org/downloads.html (_Compile From Sources_).

Who volunteers to write some lines to help me and others to understand it?

**Comment by fmontesi** [comment]
# Linux

## Compile
```
git clone https://github.com/jolie/jolie.git
cd jolie
mvn install
```
This prepares a Jolie installation inside of directory `dist`.

## Set up Jolie for the local user
Now one can use `scripts/dev-setup.sh ~/bin` to set up a working installation of Jolie for the local user (assuming `~/bin` is in `$PATH`). This will create launch scripts in `~/bin` and put all Jolie libraries in `~/bin/jolie-dist`.

## Create a global installer
After compilation, one can (I'm assuming the user is still in the `jolie` directory, hence the initial `cd ..`):
```
cd ..
git clone https://github.com/jolie/release_tools
cd release_tools/jolie_installer
mvn install
cd ..
jolie release.ol ../jolie
```
Now you have an installer in `release/jolie_installer.jar`, which you can launch by using `java -jar jolie_installer.jar`.

The problem with this is that it requires having a working Jolie installation to perform the last step. :-\
Maybe we should simply improve `scripts/dev-setup.sh` to take an optional second parameter for the libraries, such that one could launch `sudo scripts/dev-setup.sh /usr/bin /usr/lib` or something like that. What do you think?

**Comment by fmontesi** [comment]
Hi all @jolie/developers . Any news on this? Can somebody update the page? See my description above where I put some instructions.

**Comment by thesave** [comment]
Hi, 

I took a shot at it. I replaced the old guidelines based on Ant with what Fabrizio wrote above (leaving out the part on the installer).
I modified also the part on Windows, but I need someone with experience with that OS to check it. @bmaschio can you please have a look under the "Compile from Sources" tab at [1] and check that the procedure for Windows there is correct?
Also, please, let me know if there are further instructions for Windows users (like the script mentioned by Fabrizio) to have Jolie installed in their Windows system.

[1] https://www.jolie-lang.org/downloads.html

**Comment by fmontesi** [comment]
Great, thx @thesave :)

@bmaschio and @mmontesi, any suggestions for improving the Windows instructions? Feel free to propose page edits.
