### ISSUE TITLE
Slideshare broken

### ISSUE THREAD

**Issue by fmontesi** [jolie/website#3]
I'm getting this error from the slideshare service on the jolie website server:

May 12, 2015 4:11:27 PM jolie.Interpreter logInfo
INFO: [slideshare.ol] Request-Response input operation output value TypeMismatch (operation get_slideshows_by_user): Unexpected child node: #Message.Slideshow.ThumbnailXXLargeURL

Anybody? I have my hands full until tomorrow I think. :-\

**Comment by thesave** [comment]
Do you think just updating the interface should do it?

**Comment by fmontesi** [comment]
Yes. Have you tested it?

**Comment by thesave** [comment]
Doing it right now

**Comment by thesave** [comment]
fixed

**Comment by fmontesi** [comment]
Awesome, thanks. :+1:

**Comment by fmontesi** [comment]
Actually, nope. :-) Now I get this, how does it work for you?

May 12, 2015 7:30:20 PM jolie.Interpreter logInfo
INFO: [slideshare.ol] Request-Response input operation output value TypeMismatch (operation get_slideshows_by_user): Unexpected child node: #Message.Slideshow.ThumbnailXLargeURL

**Comment by fmontesi** [comment]
Works now with the latest commit!

**Comment by thesave** [comment]
yeah, committed but not pushed (I am still used to svn)
