### ISSUE TITLE
DataBase.iol use of libraries and tecnology mapping table

### ISSUE THREAD

**Issue by bmaschio** [jolie/website#8]
@jolie/developers 

Hi guys I was thinking that would be nice to explain to the user how to use JDBC  drivers, it would be be also very nice to have a table that defines the typical setting for the different technologies of db

It would be also nice to have examples how to compensate for ConnectionError or other DB error

Regards

Balint

**Comment by fmontesi** [comment]
Probably the right thing to do is to refer to the respective pages of the JDBC drivers, where this is explained? I'm afraid of replicating documentation: If they update it, we should then keep it in sync.

What do you think?

If we go for this, I'd just make a table mapping each driver name to a link with the appropriate documentation.

**Comment by bmaschio** [comment]
Yes I like the idea of referring to the standard JDBC pages  like this

| driver | driver documentation |
| --- | --- |
| postgresql | https://jdbc.postgresql.org/ |

**Comment by bmaschio** [comment]
Commited 5e71ddf added SqlServer support
